name: automl_cvenv
dependencies:
  - python=2.7.13
  - pandas==0.20.3
  - Flask==0.11.1
  - pytest==2.9.2
  - numpy==1.13.1
  - scikit-learn==0.19.0
  - Werkzeug==0.12.2
  - PyYAML==3.12
  
  - scikit-learn>=0.18.1
  - deap>=1.0
  - update_checker>=0.16
  - tqdm>=4.11.2
  - pip:
      - Flask_RESTful==0.3.6
      - gunicorn==19.7.1
      - requests==2.18.3
      - tsfresh==0.9.0
      - xgboost==0.6a2
      - nskrebate>=0.3.4
      - scikit-mdr>=0.4.4
      - stopit>=1.1.1
      - tpot
      - repidml
